name: Build

on:
  push:
    branches:
      - master

jobs:
  # build-other-platform:
  #   permissions:
  #     contents: write

  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       os: [macos-latest, ubuntu-latest, windows-latest]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Install Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '20.10.0'

  #   - name: Enable corepack
  #     run: corepack enable

  #   - name: Update yarn
  #     run: yarn set version stable

  #   - name: Set nodeLinker
  #     run: yarn config set nodeLinker node-modules

  #   - name: Install dependencies
  #     run: yarn install

  #   # Add conditional step to install Snapcraft only on Ubuntu
  #   - name: Install Snapcraft
  #     if: runner.os == 'Linux'
  #     run: sudo snap install snapcraft --classic

  #   # Build application for other configurations
  #   - name: Build application
  #     run: yarn dist
  #     env:
  #       GH_TOKEN: ${{ secrets.GH_TOKEN }}

  #   # Add this step to upload to GitHub Release
  #   - name: Upload to GitHub Release
  #     uses: softprops/action-gh-release@v1
  #     with:
  #       files: dist/*.@(exe|dmg|snap|deb|rpm|freebsd|tar.gz)
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       tag_name: v1.0.1
  #       name: 鼎小夏
  #       draft: false
  #       prerelease: false

  build-linux-arm64:
    permissions:
      contents: write

    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Enable corepack
      run: corepack enable

    - name: Update yarn
      run: yarn set version stable

    - name: Set nodeLinker
      run: yarn config set nodeLinker node-modules

    - name: Install dependencies
      run: yarn install

    # Add conditional step to install Snapcraft only on Ubuntu
    - name: Install Snapcraft
      if: runner.os == 'Linux'
      run: sudo snap install snapcraft --classic

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Install Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Create and use a new Buildx builder
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap


    - name: Build Docker image
      run: docker buildx build --platform linux/arm64 -t user/my-arm-app:latest --load .

    - name: Run Snapcraft in Docker
      run: |
        docker run --rm --privileged \
          -v $PWD:/workspace \
          -w /workspace \
          multiarch/qemu-user-static --reset -p yes
        docker run --rm \
          -v $PWD:/workspace \
          -w /workspace \
          snapcore/snapcraft:stable \
          bash -c "apt-get update && apt-get install -y snapcraft && snapcraft --target-arch=arm64"

    # Build application for other configurations
    - name: Build application
      run: yarn dist
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    # Add this step to upload to GitHub Release
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.snap
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v1.0.0
        name: 鼎小夏
        draft: false
        prerelease: false
